kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lvm-vol001
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-driver-lvm-striped
  volumeMode: Block
  resources:
    requests:
      storage: 2Gi

